title: "robertoesteban.dev"
description: "Portfolio profesional de Roberto Esteban Olivares"
baseurl: "" 
url: "https://estebanolroberto.github.io"
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Roberto Esteban Olivares"
  avatar: "/assets/images/roberto.jpg"  # AsegÃºrate de que la imagen estÃ© ahÃ­
  bio: "ğŸ“Š Data Engineer & Analyst. Apasionado por los datos, la automatizaciÃ³n y la eficiencia tecnolÃ³gica."
  location: "ğŸ‡ªğŸ‡¸ EspaÃ±a"
  links:
    - label: "ğŸ’¼ LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/roberto-esteban-olivares/"
    - label: "ğŸ± GitHub"
      icon: "fab fa-github"
      url: "https://github.com/estebanolroberto"
    - label: "ğŸ“§ Email"
      icon: "fas fa-envelope"
      url: "mailto:robertoestebanolivares@gmail.com"
    - label: "ğŸ“„ CV"
      icon: "fas fa-file-pdf"
      url: "/assets/CV_RobertoEstebanOlivares.pdf"
    
collections:
  projects:
    output: true
    permalink: /projects/:path/
